"""UMLS semantic types (TUIs) indexed by cTAKES' shipped ``sno_rx_16ab`` dictionary.

DO NOT EDIT BY HAND. Generated by ``tools/extract_ctakes_tuis.py`` from an import
of the dictionary cTAKES ships (ctakes_shipped_sno_rx_16ab).

cTAKES indexes only 49 of the ~127 UMLS semantic types. Restricting a dictionary
build to this set is what separates cTAKES-like precision from the much noisier
result of taking every SNOMEDCT_US + RXNORM concept.

The restriction is TUI-level, not group-level -- T005 "Virus" (DISORDER) and
T017 "Anatomical Structure" (ANATOMY) are both excluded while other members of
their groups are kept, so filtering by semantic group would not reproduce it.

Generated 2026-09-18.

Derived from Apache cTAKES, Apache License 2.0.
"""

from __future__ import annotations

__all__ = ["CTAKES_TUIS", "CTAKES_TUI_NAMES"]

#: The 49 TUIs cTAKES' default dictionary indexes.
CTAKES_TUIS: frozenset[str] = frozenset({
    'T019',  # DISORDER: Congenital Abnormality
    'T020',  # DISORDER: Acquired Abnormality
    'T021',  # ANATOMY: Fully Formed Anatomical Structure
    'T022',  # ANATOMY: Body System
    'T023',  # ANATOMY: Body Part, Organ, or Organ Component
    'T024',  # ANATOMY: Tissue
    'T025',  # ANATOMY: Cell
    'T026',  # ANATOMY: Cell Component
    'T029',  # ANATOMY: Body Location or Region
    'T030',  # ANATOMY: Body Space or Junction
    'T033',  # FINDING: Finding
    'T034',  # LAB: Laboratory or Test Result
    'T037',  # DISORDER: Injury or Poisoning
    'T040',  # FINDING: Organism Function
    'T041',  # FINDING: Mental Process
    'T042',  # FINDING: Organ or Tissue Function
    'T043',  # FINDING: Cell Function
    'T044',  # FINDING: Molecular Function
    'T045',  # FINDING: Genetic Function
    'T046',  # FINDING: Pathologic Function
    'T047',  # DISORDER: Disease or Syndrome
    'T048',  # DISORDER: Mental or Behavioral Dysfunction
    'T049',  # DISORDER: Cell or Molecular Dysfunction
    'T050',  # DISORDER: Experimental Model of Disease
    'T056',  # FINDING: Daily or Recreational Activity
    'T057',  # EVENT: Occupational Activity
    'T059',  # PROCEDURE: Laboratory Procedure
    'T060',  # PROCEDURE: Diagnostic Procedure
    'T061',  # PROCEDURE: Therapeutic or Preventive Procedure
    'T109',  # DRUG: Organic Chemical
    'T114',  # DRUG: Nucleic Acid, Nucleoside, or Nucleotide
    'T116',  # DRUG: Amino Acid, Peptide, or Protein
    'T121',  # DRUG: Pharmacologic Substance
    'T122',  # DRUG: Biomedical or Dental Material
    'T123',  # DRUG: Biologically Active Substance
    'T125',  # DRUG: Hormone
    'T126',  # DRUG: Enzyme
    'T127',  # DRUG: Vitamin
    'T129',  # DRUG: Immunologic Factor
    'T130',  # DRUG: Indicator, Reagent, or Diagnostic Aid
    'T131',  # DRUG: Hazardous or Poisonous Substance
    'T184',  # FINDING: Sign or Symptom
    'T190',  # DISORDER: Anatomical Abnormality
    'T191',  # DISORDER: Neoplastic Process
    'T195',  # DRUG: Antibiotic
    'T196',  # DRUG: Element, Ion, or Isotope
    'T197',  # DRUG: Inorganic Chemical
    'T200',  # DRUG: Clinical Drug
    'T203',  # DEVICE: Drug Delivery Device
})

#: TUI -> UMLS semantic type name, for the whitelisted set only.
CTAKES_TUI_NAMES: dict[str, str] = {
    'T019': 'Congenital Abnormality',
    'T020': 'Acquired Abnormality',
    'T021': 'Fully Formed Anatomical Structure',
    'T022': 'Body System',
    'T023': 'Body Part, Organ, or Organ Component',
    'T024': 'Tissue',
    'T025': 'Cell',
    'T026': 'Cell Component',
    'T029': 'Body Location or Region',
    'T030': 'Body Space or Junction',
    'T033': 'Finding',
    'T034': 'Laboratory or Test Result',
    'T037': 'Injury or Poisoning',
    'T040': 'Organism Function',
    'T041': 'Mental Process',
    'T042': 'Organ or Tissue Function',
    'T043': 'Cell Function',
    'T044': 'Molecular Function',
    'T045': 'Genetic Function',
    'T046': 'Pathologic Function',
    'T047': 'Disease or Syndrome',
    'T048': 'Mental or Behavioral Dysfunction',
    'T049': 'Cell or Molecular Dysfunction',
    'T050': 'Experimental Model of Disease',
    'T056': 'Daily or Recreational Activity',
    'T057': 'Occupational Activity',
    'T059': 'Laboratory Procedure',
    'T060': 'Diagnostic Procedure',
    'T061': 'Therapeutic or Preventive Procedure',
    'T109': 'Organic Chemical',
    'T114': 'Nucleic Acid, Nucleoside, or Nucleotide',
    'T116': 'Amino Acid, Peptide, or Protein',
    'T121': 'Pharmacologic Substance',
    'T122': 'Biomedical or Dental Material',
    'T123': 'Biologically Active Substance',
    'T125': 'Hormone',
    'T126': 'Enzyme',
    'T127': 'Vitamin',
    'T129': 'Immunologic Factor',
    'T130': 'Indicator, Reagent, or Diagnostic Aid',
    'T131': 'Hazardous or Poisonous Substance',
    'T184': 'Sign or Symptom',
    'T190': 'Anatomical Abnormality',
    'T191': 'Neoplastic Process',
    'T195': 'Antibiotic',
    'T196': 'Element, Ion, or Isotope',
    'T197': 'Inorganic Chemical',
    'T200': 'Clinical Drug',
    'T203': 'Drug Delivery Device',
}
