"""UMLS semantic type (TUI) and semantic group tables for cTAKES parity.

DO NOT EDIT BY HAND. Generated by ``tools/transcode_semantic_tui.py`` from
apache/ctakes 7.0.0-SNAPSHOT.

Source files:
  * ctakes-core/src/main/java/org/apache/ctakes/core/util/annotation/SemanticTui.java
  * ctakes-core/src/main/java/org/apache/ctakes/core/util/annotation/SemanticGroup.java
  * ctakes-type-system/src/main/java/org/apache/ctakes/typesystem/type/constants/CONST.java

Generated 2026-09-17.

Derived from Apache cTAKES, Apache License 2.0.
"""

from __future__ import annotations

from enum import Enum

__all__ = [
    "CTAKES_VERSION",
    "MAJOR_GROUPS",
    "SemanticGroup",
    "TUI_TO_GROUP",
    "TUI_NAMES",
    "group_for_tui",
    "groups_for_tuis",
    "best_group",
    "normalize_tui",
]

CTAKES_VERSION = "7.0.0-SNAPSHOT"


class SemanticGroup(Enum):
    """The 17 cTAKES semantic groups.

    ``code`` is cTAKES' internal ``NE_TYPE_ID_*`` value. It is not contiguous
    (there is no 4) and the twelve minor groups use the 1001+ range. The codes
    matter because :func:`best_group` orders by them.
    """

    def __init__(self, code: int, label: str, long_label: str) -> None:
        self.code = code
        self.label = label
        self.long_label = long_label

    DRUG = (1, 'Drug', 'Medication')
    DISORDER = (2, 'Disorder', 'Disease/Disorder')
    FINDING = (3, 'Finding', 'Sign/Symptom')
    PROCEDURE = (5, 'Procedure', 'Procedure')
    ANATOMY = (6, 'Anatomy', 'Anatomical Site')
    CLINICAL_ATTRIBUTE = (7, 'Attribute', 'Clinical Attribute')
    DEVICE = (8, 'Device', 'Device')
    LAB = (9, 'Lab', 'Lab')
    PHENOMENON = (10, 'Phenomenon', 'Phenomenon')
    SUBJECT = (1001, 'Subject', 'Subject')
    TITLE = (1002, 'Title', 'Person Title')
    EVENT = (1003, 'Event', 'Event')
    ENTITY = (1004, 'Entity', 'Entity')
    TIME = (1005, 'Time', 'Timex3')
    MODIFIER = (1006, 'Modifier', 'Modifier')
    LAB_MODIFIER = (1007, 'LabModifier', 'Lab Modifier')
    UNKNOWN = (0, 'Unknown', 'Unknown Semantic Group')

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<SemanticGroup.{self.name} code={self.code}>"


#: Groups cTAKES calls "major" -- the five most deployments actually consume.
MAJOR_GROUPS = (
    SemanticGroup.DRUG,
    SemanticGroup.DISORDER,
    SemanticGroup.FINDING,
    SemanticGroup.PROCEDURE,
    SemanticGroup.ANATOMY,
)

#: UMLS TUI -> semantic group. 136 entries.
TUI_TO_GROUP: dict[str, SemanticGroup] = {
    'T116': SemanticGroup.DRUG,
    'T020': SemanticGroup.DISORDER,
    'T052': SemanticGroup.EVENT,
    'T100': SemanticGroup.SUBJECT,
    'T003': SemanticGroup.ENTITY,
    'T087': SemanticGroup.DRUG,
    'T011': SemanticGroup.ENTITY,
    'T190': SemanticGroup.DISORDER,
    'T008': SemanticGroup.ENTITY,
    'T017': SemanticGroup.ANATOMY,
    'T195': SemanticGroup.DRUG,
    'T194': SemanticGroup.ENTITY,
    'T123': SemanticGroup.DRUG,
    'T007': SemanticGroup.ENTITY,
    'T031': SemanticGroup.FINDING,
    'T022': SemanticGroup.ANATOMY,
    'T053': SemanticGroup.FINDING,
    'T038': SemanticGroup.PHENOMENON,
    'T012': SemanticGroup.ENTITY,
    'T029': SemanticGroup.ANATOMY,
    'T091': SemanticGroup.TITLE,
    'T122': SemanticGroup.DRUG,
    'T023': SemanticGroup.ANATOMY,
    'T030': SemanticGroup.ANATOMY,
    'T118': SemanticGroup.DRUG,
    'T026': SemanticGroup.ANATOMY,
    'T043': SemanticGroup.FINDING,
    'T025': SemanticGroup.ANATOMY,
    'T019': SemanticGroup.DISORDER,
    'T103': SemanticGroup.DRUG,
    'T120': SemanticGroup.DRUG,
    'T104': SemanticGroup.DRUG,
    'T185': SemanticGroup.FINDING,
    'T201': SemanticGroup.CLINICAL_ATTRIBUTE,
    'T200': SemanticGroup.DRUG,
    'T077': SemanticGroup.FINDING,
    'T049': SemanticGroup.DISORDER,
    'T088': SemanticGroup.DRUG,
    'T060': SemanticGroup.PROCEDURE,
    'T056': SemanticGroup.FINDING,
    'T047': SemanticGroup.DISORDER,
    'T203': SemanticGroup.DEVICE,
    'T065': SemanticGroup.PROCEDURE,
    'T069': SemanticGroup.PHENOMENON,
    'T111': SemanticGroup.ENTITY,
    'T196': SemanticGroup.DRUG,
    'T050': SemanticGroup.DISORDER,
    'T018': SemanticGroup.ANATOMY,
    'T071': SemanticGroup.ENTITY,
    'T126': SemanticGroup.DRUG,
    'T051': SemanticGroup.EVENT,
    'T099': SemanticGroup.SUBJECT,
    'T021': SemanticGroup.ANATOMY,
    'T013': SemanticGroup.ENTITY,
    'T033': SemanticGroup.FINDING,
    'T004': SemanticGroup.ENTITY,
    'T168': SemanticGroup.DRUG,
    'T169': SemanticGroup.FINDING,
    'T045': SemanticGroup.FINDING,
    'T083': SemanticGroup.ENTITY,
    'T028': SemanticGroup.FINDING,
    'T064': SemanticGroup.EVENT,
    'T102': SemanticGroup.SUBJECT,
    'T096': SemanticGroup.SUBJECT,
    'T068': SemanticGroup.PHENOMENON,
    'T093': SemanticGroup.ENTITY,
    'T058': SemanticGroup.PROCEDURE,
    'T131': SemanticGroup.DRUG,
    'T125': SemanticGroup.DRUG,
    'T016': SemanticGroup.SUBJECT,
    'T078': SemanticGroup.FINDING,
    'T129': SemanticGroup.DRUG,
    'T055': SemanticGroup.FINDING,
    'T197': SemanticGroup.DRUG,
    'T037': SemanticGroup.DISORDER,
    'T170': SemanticGroup.FINDING,
    'T009': SemanticGroup.ENTITY,
    'T130': SemanticGroup.DRUG,
    'T171': SemanticGroup.ENTITY,
    'T059': SemanticGroup.PROCEDURE,
    'T034': SemanticGroup.LAB,
    'T119': SemanticGroup.DRUG,
    'T015': SemanticGroup.ENTITY,
    'T063': SemanticGroup.PROCEDURE,
    'T066': SemanticGroup.PROCEDURE,
    'T074': SemanticGroup.DEVICE,
    'T041': SemanticGroup.FINDING,
    'T073': SemanticGroup.DEVICE,
    'T048': SemanticGroup.DISORDER,
    'T044': SemanticGroup.FINDING,
    'T085': SemanticGroup.FINDING,
    'T191': SemanticGroup.DISORDER,
    'T114': SemanticGroup.DRUG,
    'T070': SemanticGroup.PHENOMENON,
    'T124': SemanticGroup.DRUG,
    'T086': SemanticGroup.FINDING,
    'T057': SemanticGroup.EVENT,
    'T090': SemanticGroup.SUBJECT,
    'T115': SemanticGroup.DRUG,
    'T109': SemanticGroup.DRUG,
    'T032': SemanticGroup.SUBJECT,
    'T040': SemanticGroup.FINDING,
    'T001': SemanticGroup.ENTITY,
    'T092': SemanticGroup.ENTITY,
    'T042': SemanticGroup.FINDING,
    'T046': SemanticGroup.FINDING,
    'T072': SemanticGroup.ENTITY,
    'T067': SemanticGroup.PHENOMENON,
    'T039': SemanticGroup.FINDING,
    'T121': SemanticGroup.DRUG,
    'T002': SemanticGroup.ENTITY,
    'T101': SemanticGroup.SUBJECT,
    'T098': SemanticGroup.SUBJECT,
    'T097': SemanticGroup.SUBJECT,
    'T094': SemanticGroup.ENTITY,
    'T080': SemanticGroup.MODIFIER,
    'T081': SemanticGroup.LAB_MODIFIER,
    'T192': SemanticGroup.FINDING,
    'T014': SemanticGroup.ENTITY,
    'T062': SemanticGroup.PROCEDURE,
    'T075': SemanticGroup.DEVICE,
    'T006': SemanticGroup.DISORDER,
    'T089': SemanticGroup.ENTITY,
    'T167': SemanticGroup.DRUG,
    'T095': SemanticGroup.ENTITY,
    'T054': SemanticGroup.FINDING,
    'T184': SemanticGroup.FINDING,
    'T082': SemanticGroup.MODIFIER,
    'T110': SemanticGroup.DRUG,
    'T024': SemanticGroup.ANATOMY,
    'T079': SemanticGroup.TIME,
    'T061': SemanticGroup.PROCEDURE,
    'T005': SemanticGroup.DISORDER,
    'T127': SemanticGroup.DRUG,
    'T010': SemanticGroup.ENTITY,
    'T204': SemanticGroup.ENTITY,
}

#: UMLS TUI -> UMLS semantic type name.
TUI_NAMES: dict[str, str] = {
    'T116': 'Amino Acid, Peptide, or Protein',
    'T020': 'Acquired Abnormality',
    'T052': 'Activity',
    'T100': 'Age Group',
    'T003': 'Alga',
    'T087': 'Amino Acid Sequence',
    'T011': 'Amphibian',
    'T190': 'Anatomical Abnormality',
    'T008': 'Animal',
    'T017': 'Anatomical Structure',
    'T195': 'Antibiotic',
    'T194': 'Archaeon',
    'T123': 'Biologically Active Substance',
    'T007': 'Bacterium',
    'T031': 'Body Substance',
    'T022': 'Body System',
    'T053': 'Behavior',
    'T038': 'Biologic Function',
    'T012': 'Bird',
    'T029': 'Body Location or Region',
    'T091': 'Biomedical Occupation or Discipline',
    'T122': 'Biomedical or Dental Material',
    'T023': 'Body Part, Organ, or Organ Component',
    'T030': 'Body Space or Junction',
    'T118': 'Carbohydrate',
    'T026': 'Cell Component',
    'T043': 'Cell Function',
    'T025': 'Cell',
    'T019': 'Congenital Abnormality',
    'T103': 'Chemical',
    'T120': 'Chemical Viewed Functionally',
    'T104': 'Chemical Viewed Structurally',
    'T185': 'Classification',
    'T201': 'Clinical Attribute',
    'T200': 'Clinical Drug',
    'T077': 'Conceptual Entity',
    'T049': 'Cell or Molecular Dysfunction',
    'T088': 'Carbohydrate Sequence',
    'T060': 'Diagnostic Procedure',
    'T056': 'Daily or Recreational Activity',
    'T047': 'Disease or Syndrome',
    'T203': 'Drug Delivery Device',
    'T065': 'Educational Activity',
    'T069': 'Environmental Effect of Humans',
    'T111': 'Eicosanoid',
    'T196': 'Element, Ion, or Isotope',
    'T050': 'Experimental Model of Disease',
    'T018': 'Embryonic Structure',
    'T071': 'Entity',
    'T126': 'Enzyme',
    'T051': 'Event',
    'T099': 'Family Group',
    'T021': 'Fully Formed Anatomical Structure',
    'T013': 'Fish',
    'T033': 'Finding',
    'T004': 'Fungus',
    'T168': 'Food',
    'T169': 'Functional Concept',
    'T045': 'Genetic Function',
    'T083': 'Geographic Area',
    'T028': 'Gene or Genome',
    'T064': 'Governmental or Regulatory Activity',
    'T102': 'Group Attribute',
    'T096': 'Group',
    'T068': 'Human-caused Phenomenon or Process',
    'T093': 'Health Care Related Organization',
    'T058': 'Health Care Activity',
    'T131': 'Hazardous or Poisonous Substance',
    'T125': 'Hormone',
    'T016': 'Human',
    'T078': 'Idea or Concept',
    'T129': 'Immunologic Factor',
    'T055': 'Individual Behavior',
    'T197': 'Inorganic Chemical',
    'T037': 'Injury or Poisoning',
    'T170': 'Intellectual Product',
    'T009': 'Invertebrate',
    'T130': 'Indicator, Reagent, or Diagnostic Aid',
    'T171': 'Language',
    'T059': 'Laboratory Procedure',
    'T034': 'Laboratory or Test Result',
    'T119': 'Lipid',
    'T015': 'Mammal',
    'T063': 'Molecular Biology Research Technique',
    'T066': 'Machine Activity',
    'T074': 'Medical Device',
    'T041': 'Mental Process',
    'T073': 'Manufactured Object',
    'T048': 'Mental or Behavioral Dysfunction',
    'T044': 'Molecular Function',
    'T085': 'Molecular Sequence',
    'T191': 'Neoplastic Process',
    'T114': 'Nucleic Acid, Nucleoside, or Nucleotide',
    'T070': 'Natural Phenomenon or Process',
    'T124': 'Neuroreactive Substance or Biogenic Amine',
    'T086': 'Nucleotide Sequence',
    'T057': 'Occupational Activity',
    'T090': 'Occupation or Discipline',
    'T115': 'Organophosphorous Compound',
    'T109': 'Organic Chemical',
    'T032': 'Organism Attribute',
    'T040': 'Organism Function',
    'T001': 'Organism',
    'T092': 'Organization',
    'T042': 'Organ or Tissue Function',
    'T046': 'Pathologic Function',
    'T072': 'Physical Object',
    'T067': 'Phenomenon or Process',
    'T039': 'Physiologic Function',
    'T121': 'Pharmacologic Substance',
    'T002': 'Plant',
    'T101': 'Patient or Disabled Group',
    'T098': 'Population Group',
    'T097': 'Professional or Occupational Group',
    'T094': 'Professional Society',
    'T080': 'Qualitative Concept',
    'T081': 'Quantitative Concept',
    'T192': 'Receptor',
    'T014': 'Reptile',
    'T062': 'Research Activity',
    'T075': 'Research Device',
    'T006': 'Rickettsia or Chlamydia',
    'T089': 'Regulation or Law',
    'T167': 'Substance',
    'T095': 'Self-help or Relief Organization',
    'T054': 'Social Behavior',
    'T184': 'Sign or Symptom',
    'T082': 'Spatial Concept',
    'T110': 'Steroid',
    'T024': 'Tissue',
    'T079': 'Temporal Concept',
    'T061': 'Therapeutic or Preventive Procedure',
    'T005': 'Virus',
    'T127': 'Vitamin',
    'T010': 'Vertebrate',
    'T204': 'Eukaryote',
}


def normalize_tui(tui: str | int) -> str:
    """Normalize a TUI to cTAKES' ``T###`` spelling.

    Accepts ``"T047"``, ``"t47"``, ``47`` or ``"47"``. MRSTY.RRF already uses
    the zero-padded form, but callers passing ints are easy to get wrong.

    A negative int is rejected rather than formatted into the unusable
    ``"T-01"``, which would otherwise sail through as a silent ``UNKNOWN``
    group lookup.
    """
    if isinstance(tui, int):
        if tui < 0:
            raise ValueError(f"not a TUI: {tui!r}")
        return f"T{tui:03d}"
    text = tui.strip().upper()
    if text.startswith("T"):
        text = text[1:]
    if not text.isdigit():
        raise ValueError(f"not a TUI: {tui!r}")
    return f"T{int(text):03d}"


def group_for_tui(tui: str | int) -> SemanticGroup:
    """Map a single TUI to its group, defaulting to ``UNKNOWN``."""
    return TUI_TO_GROUP.get(normalize_tui(tui), SemanticGroup.UNKNOWN)


def best_group(groups) -> SemanticGroup:
    """Pick the most specific group, reproducing cTAKES' ``getBestGroup``.

    cTAKES implements this as ``stream().min(BestGrouper)`` where
    ``BestGrouper.compare(g1, g2)`` returns ``g2.code - g1.code`` and forces
    ``UNKNOWN`` to sort last. ``min`` with that inverted comparator selects the
    member with the **highest** code, so that is what we do here.

    Note the upstream javadoc on ``BestGrouper`` says "e.g. Procedure is before
    Phenomenon", which contradicts the code it documents (PROCEDURE=5 loses to
    PHENOMENON=10 under highest-code-wins). We follow the code, since that is
    what the running Java pipeline does and therefore what parity testing will
    compare against. If a future cTAKES release fixes the comparator, this
    function must change with it.
    """
    best = SemanticGroup.UNKNOWN
    for group in groups:
        if group is SemanticGroup.UNKNOWN:
            continue
        if best is SemanticGroup.UNKNOWN or group.code > best.code:
            best = group
    return best


def groups_for_tuis(tuis) -> set:
    """All groups implied by a collection of TUIs."""
    return {group_for_tui(t) for t in tuis}
