#!/usr/bin/env python3
"""Extract the TUI whitelist cTAKES' shipped dictionary was built from.

The ``sno_rx_16ab`` dictionary cTAKES distributes indexes only **49** of the 127
UMLS semantic types. That restriction is the single largest driver of its
precision relative to a naive SNOMEDCT_US+RXNORM extract, and it is not recorded
anywhere in the cTAKES source -- it was chosen interactively when the dictionary
was built. But it is recoverable by reading which TUIs the shipped database
actually contains.

This captures that whitelist as a checked-in Python module so it survives
without a cTAKES install on hand, and so applying it to a *current* UMLS release
is a one-flag operation.

The filter is genuinely TUI-level, not semantic-group-level: T005 "Virus" is in
the DISORDER group but excluded, and T017 "Anatomical Structure" is in ANATOMY
but excluded. Filtering by group would be measurably wrong.

Requires the shipped dictionary to have been imported first::

    python tools/import_ctakes_dictionary.py --script <...>/sno_rx_16ab.script \\
        --out data/umls_ctakes_16ab.sqlite
    python tools/extract_ctakes_tuis.py --db data/umls_ctakes_16ab.sqlite
"""

from __future__ import annotations

import argparse
import datetime as _dt
import sqlite3
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from umlsmatch.umls.semantic_tui import TUI_NAMES, group_for_tui

TEMPLATE = '''"""UMLS semantic types (TUIs) indexed by cTAKES' shipped ``sno_rx_16ab`` dictionary.

DO NOT EDIT BY HAND. Generated by ``tools/extract_ctakes_tuis.py`` from an import
of the dictionary cTAKES ships ({source}).

cTAKES indexes only {n} of the ~127 UMLS semantic types. Restricting a dictionary
build to this set is what separates cTAKES-like precision from the much noisier
result of taking every SNOMEDCT_US + RXNORM concept.

The restriction is TUI-level, not group-level -- T005 "Virus" (DISORDER) and
T017 "Anatomical Structure" (ANATOMY) are both excluded while other members of
their groups are kept, so filtering by semantic group would not reproduce it.

Generated {stamp}.

Derived from Apache cTAKES, Apache License 2.0.
"""

from __future__ import annotations

__all__ = ["CTAKES_TUIS", "CTAKES_TUI_NAMES"]

#: The {n} TUIs cTAKES' default dictionary indexes.
CTAKES_TUIS: frozenset[str] = frozenset({{
{tuis}
}})

#: TUI -> UMLS semantic type name, for the whitelisted set only.
CTAKES_TUI_NAMES: dict[str, str] = {{
{named}
}}
'''


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--db", type=Path, default=Path("data/umls_ctakes_16ab.sqlite"))
    ap.add_argument("--out", type=Path, default=Path("src/umlsmatch/umls/ctakes_tuis.py"))
    args = ap.parse_args()

    if not args.db.is_file():
        sys.exit(
            f"error: {args.db} not found.\n"
            "Run tools/import_ctakes_dictionary.py first."
        )

    conn = sqlite3.connect(f"file:{args.db}?mode=ro", uri=True)
    tuis = sorted({r[0] for r in conn.execute("SELECT DISTINCT tui FROM concept_tui")})
    source = dict(conn.execute("SELECT key, value FROM meta")).get("source", "unknown")
    conn.close()

    if not tuis:
        sys.exit("error: no TUIs found in concept_tui")

    body = "\n".join(
        f"    {t!r},  # {group_for_tui(t).name}: {TUI_NAMES.get(t, '')}" for t in tuis
    )
    named = "\n".join(f"    {t!r}: {TUI_NAMES.get(t, '')!r}," for t in tuis)

    rendered = TEMPLATE.format(
        n=len(tuis),
        source=source,
        stamp=_dt.date.today().isoformat(),
        tuis=body,
        named=named,
    )
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(rendered, encoding="utf-8")

    from collections import Counter

    dist = Counter(group_for_tui(t).name for t in tuis)
    print(f"extracted {len(tuis)} TUIs from {args.db}")
    for g, c in dist.most_common():
        print(f"  {g:<12} {c}")
    print(f"\nwrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
